server:
  port: 1001

security:
  oauth2:
    client:
      user-authorization-uri: http://localhost:1000/oauth/authorize
      access-token-uri: http://localhost:1000/oauth/token
      client-id: xiaoyu
      client-secret: xiaoyu
      scope: read

    resource:
      jwt:
        key-uri: http://localhost:1000/oauth/token_key

    sso:
      login-path: /login

  basic:
    enabled: false

  sessions: stateless











